name: Publish Docker

on:
  push:
    branches:
      - test
      - stage
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Slack Notify Begin
      continue-on-error: true
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'üîÉ Build: ERC20 Service on ${{ steps.extract_branch.outputs.branch }} (${{ github.sha }})'
    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.GH_ACTIONS_TOKEN }}
        submodules: true
    - uses: tixl/aws-ecr-action@master
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: tixl/${{ steps.extract_branch.outputs.branch }}-erc20-service
        region: eu-central-1
        tags: latest,${{ github.sha }}
        extra_build_args: --build-arg GITHUB_TOKEN=${{ secrets.GH_ACTIONS_TOKEN }}
    - name: Slack Notify Success
      continue-on-error: true
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: '‚úÖ Build: ERC20 Service on ${{ steps.extract_branch.outputs.branch }} (${{ github.sha }})'
    - name: Slack Notify Failure
      continue-on-error: true
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: '‚ùå Build: ERC20 Service on ${{ steps.extract_branch.outputs.branch }} (${{ github.sha }})'
